# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Zachary R Newton
title_meta: Designer/Developer
email: zacharyrnewton@gmail.com
description: Zachary R Newton is a freelance designer & developer who has been working professionally since 2013. He loves to solve problems and make visually stunning products. Zachary also enjoys sharing his experiences and thoughts in his blog. Keep up with new projects he is working on, subscribe to his newsletter and go follow him on Twitter.
baseurl: "/zacharyrnewton2.0" # the subpath of your site, e.g. /blog
url: "https://zacharyrnewton.github.io" # the base hostname & protocol for your site, e.g. http://example.com
enforce_ssl: zacharyrnewton.com

twitter_path: https://twitter.com/_zacharyrnewton
instagram_path: https://www.instagram.com/zacharyrnewton/
facebook_path: https://www.facebook.com/zacharyrnewton
youtube_path: https://www.youtube.com/channel/UCWfGm9LosEAeQVMZsp2HgAw
github_path: https://github.com/zacharyrnewton

linkFromTwitter: https%3A%2F%2Fzacharyrnewton.com%2f
twitterUser: _zacharyrnewton

pathToBlogImgBin: /assets/img/blog/
# Build settings
permalink: pretty
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-autoprefixer
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: _sass
collections:
  casestudies:
    output: true
